#include: package:flutter_lints/flutter.yaml
include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore
    avoid_print: ignore
    unintended_html_in_doc_comment: ignore
